<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetMind.Common\NetMind.Common.csproj" />
    <ProjectReference Include="..\NetMind.Models\NetMind.Models.csproj" />
    <ProjectReference Include="..\NetMind.Repository\NetMind.Repository.csproj" />
  </ItemGroup>

</Project>
