-- NetMind P0.2 database initialization script.
-- Target database: PostgreSQL
-- This script is idempotent and safe to run repeatedly.

BEGIN;

CREATE TABLE IF NOT EXISTS mind_map (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    root_node_id BIGINT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ NULL
);

CREATE TABLE IF NOT EXISTS node (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    map_id BIGINT NOT NULL,
    parent_id BIGINT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT NULL,
    order_no INTEGER NOT NULL DEFAULT 0,
    position_x DOUBLE PRECISION NULL,
    position_y DOUBLE PRECISION NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ NULL,
    CONSTRAINT fk_node_map
        FOREIGN KEY (map_id)
        REFERENCES mind_map (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_node_parent
        FOREIGN KEY (parent_id)
        REFERENCES node (id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS node_relation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL,
    target_id BIGINT NOT NULL,
    relation_type VARCHAR(50) NOT NULL,
    weight DOUBLE PRECISION NOT NULL DEFAULT 1,
    map_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ NULL,
    CONSTRAINT fk_node_relation_source
        FOREIGN KEY (source_id)
        REFERENCES node (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_node_relation_target
        FOREIGN KEY (target_id)
        REFERENCES node (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_node_relation_map
        FOREIGN KEY (map_id)
        REFERENCES mind_map (id)
        ON DELETE CASCADE,
    CONSTRAINT chk_node_relation_weight_non_negative
        CHECK (weight >= 0),
    CONSTRAINT chk_node_relation_not_self
        CHECK (source_id <> target_id)
);

CREATE TABLE IF NOT EXISTS node_meta (
    node_id BIGINT NOT NULL,
    key VARCHAR(100) NOT NULL,
    value TEXT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ NULL,
    CONSTRAINT pk_node_meta
        PRIMARY KEY (node_id, key),
    CONSTRAINT fk_node_meta_node
        FOREIGN KEY (node_id)
        REFERENCES node (id)
        ON DELETE CASCADE
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_mind_map_root_node'
          AND conrelid = 'mind_map'::regclass
    ) THEN
        ALTER TABLE mind_map
            ADD CONSTRAINT fk_mind_map_root_node
            FOREIGN KEY (root_node_id)
            REFERENCES node (id)
            ON DELETE SET NULL;
    END IF;
END;
$$;

CREATE INDEX IF NOT EXISTS idx_node_map_id
    ON node (map_id)
    WHERE is_deleted = FALSE;

CREATE INDEX IF NOT EXISTS idx_node_parent_id
    ON node (parent_id)
    WHERE is_deleted = FALSE;

CREATE INDEX IF NOT EXISTS idx_node_map_parent_order
    ON node (map_id, parent_id, order_no)
    WHERE is_deleted = FALSE;

CREATE INDEX IF NOT EXISTS idx_node_title_content_fulltext
    ON node
    USING GIN (to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(content, '')))
    WHERE is_deleted = FALSE;

ALTER TABLE node
    ADD COLUMN IF NOT EXISTS position_x DOUBLE PRECISION;

ALTER TABLE node
    ADD COLUMN IF NOT EXISTS position_y DOUBLE PRECISION;

CREATE INDEX IF NOT EXISTS idx_mind_map_not_deleted
    ON mind_map (id)
    WHERE is_deleted = FALSE;

CREATE INDEX IF NOT EXISTS idx_node_relation_source_id
    ON node_relation (source_id)
    WHERE is_deleted = FALSE;

CREATE INDEX IF NOT EXISTS idx_node_relation_target_id
    ON node_relation (target_id)
    WHERE is_deleted = FALSE;

CREATE INDEX IF NOT EXISTS idx_node_relation_type
    ON node_relation (relation_type)
    WHERE is_deleted = FALSE;

CREATE INDEX IF NOT EXISTS idx_node_relation_map_id
    ON node_relation (map_id)
    WHERE is_deleted = FALSE;

CREATE INDEX IF NOT EXISTS idx_node_relation_map_type
    ON node_relation (map_id, relation_type)
    WHERE is_deleted = FALSE;

CREATE INDEX IF NOT EXISTS idx_node_meta_key
    ON node_meta (key);

INSERT INTO mind_map (id, title, root_node_id, created_at, updated_at)
VALUES
    (1001, '产品需求知识图谱', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (1002, '技术方案知识图谱', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (1003, '项目计划知识图谱', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (id) DO UPDATE
SET title = EXCLUDED.title,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO node (id, map_id, parent_id, title, content, order_no, created_at, updated_at)
VALUES
    (2001, 1001, NULL, '需求总览', '记录产品需求、用户确认和结构化导入流程。', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2002, 1001, 2001, '用户确认', '导入数据库前允许用户调整和校验结构化数据。', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2003, 1001, 2001, '结构化导入', '将清洗后的标准结构导入数据库持久化保存。', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    (2011, 1002, NULL, '技术总览', '后端使用 WebAPI，前端使用 Vue3，数据库使用 PostgreSQL。', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2012, 1002, 2011, '后端服务', '负责数据管理、用户管理和 AI 调用。', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2013, 1002, 2011, '前端展示', '负责思维导图展示和基础交互。', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

    (2021, 1003, NULL, 'P0 数据闭环 Demo', '完成手动创建、存储和展示思维导图的最小闭环。', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2022, 1003, 2021, 'P0.1 最小工程', '建立 .NET 和 Vue3 最小可运行工程。', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2023, 1003, 2021, 'P0.2 数据库搭建', '落地 mind_map、node、node_relation、node_meta 四张最小表。', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (id) DO UPDATE
SET map_id = EXCLUDED.map_id,
    parent_id = EXCLUDED.parent_id,
    title = EXCLUDED.title,
    content = EXCLUDED.content,
    order_no = EXCLUDED.order_no,
    updated_at = CURRENT_TIMESTAMP;

UPDATE mind_map
SET root_node_id = CASE id
    WHEN 1001 THEN 2001
    WHEN 1002 THEN 2011
    WHEN 1003 THEN 2021
    ELSE root_node_id
END,
updated_at = CURRENT_TIMESTAMP
WHERE id IN (1001, 1002, 1003);

INSERT INTO node_relation (id, source_id, target_id, relation_type, weight, map_id, created_at)
VALUES
    (3001, 2002, 2003, 'depends_on', 0.80, 1001, CURRENT_TIMESTAMP),
    (3002, 2012, 2013, 'supports', 0.70, 1002, CURRENT_TIMESTAMP),
    (3003, 2022, 2023, 'next_step', 1.00, 1003, CURRENT_TIMESTAMP)
ON CONFLICT (id) DO UPDATE
SET source_id = EXCLUDED.source_id,
    target_id = EXCLUDED.target_id,
    relation_type = EXCLUDED.relation_type,
    weight = EXCLUDED.weight,
    map_id = EXCLUDED.map_id;

INSERT INTO node_meta (node_id, key, value)
VALUES
    (2001, 'source', '需求文档'),
    (2011, 'stack', 'WebAPI + Vue3 + PostgreSQL'),
    (2023, 'stage', 'P0.2')
ON CONFLICT (node_id, key) DO UPDATE
SET value = EXCLUDED.value;

SELECT setval(pg_get_serial_sequence('mind_map', 'id'), GREATEST(COALESCE((SELECT max(id) FROM mind_map), 1), 1), true);
SELECT setval(pg_get_serial_sequence('node', 'id'), GREATEST(COALESCE((SELECT max(id) FROM node), 1), 1), true);
SELECT setval(pg_get_serial_sequence('node_relation', 'id'), GREATEST(COALESCE((SELECT max(id) FROM node_relation), 1), 1), true);

COMMIT;
