-- NetMind P1.4 AI conversation record table.
-- Target database: PostgreSQL
-- This script is idempotent and safe to run repeatedly.

BEGIN;

CREATE TABLE IF NOT EXISTS ai_conversation_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    model_id VARCHAR(100) NULL,
    prompt TEXT NULL,
    context_summary TEXT NULL,
    was_context_compressed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ NULL,
    CONSTRAINT chk_ai_conversation_record_role
        CHECK (role IN ('user', 'assistant', 'system'))
);

CREATE INDEX IF NOT EXISTS idx_ai_conversation_record_conversation_id
    ON ai_conversation_record (conversation_id, created_at, id)
    WHERE is_deleted = FALSE;

CREATE INDEX IF NOT EXISTS idx_ai_conversation_record_role
    ON ai_conversation_record (role)
    WHERE is_deleted = FALSE;

CREATE INDEX IF NOT EXISTS idx_ai_conversation_record_model_id
    ON ai_conversation_record (model_id)
    WHERE is_deleted = FALSE;

COMMIT;
